### ISSUE TITLE
Authorization problem

### ISSUE THREAD

**Issue by taromero** [spreaker/grunt-aws-apigateway#3]
UPDATE (10-Dec-2015)

This was a problem related to some limitation on the number of endpoints attached to a particular Lambda function, completely unrelated to how this particular library works.

---

When I create the API, I try to make a test invoke from Gateway's UI and I got an error:

`Execution failed due to configuration error: Invalid permissions on Lambda function`

If I go to the `Integration Request` section of a particular endpoint and manually remove/attach again the Lambda function, it works. I suspect that Gateway's UI attach the proper auth policy to the Lambda function when relating it to the endpoint, while the grunt taks doesn't. Does it make sense?

Is there any (non-manual) workaround currently?

Thanks!

**Comment by pracucci** [comment]
May you share the policies of the IAM user that's calling the API Gateway APIs? Please strip any private data from the policy, like for example your AWS Account ID.

**Comment by pracucci** [comment]
The IAM user I currently use to deploy AWS Lambda + API Gateway integration, has the following policy. May you give it a try?

Remember to replace:
- `<aws account id>` with you AWS account id
- `<region>` with the AWS region
- `<role name>` with your Lambda execution role name

``` json
 {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "apigateway:*"
            ],
            "Resource": [
                "arn:aws:apigateway:<region>::/restapis/<rest api id>",
                "arn:aws:apigateway:<region>::/restapis/<rest api id>/*"
            ]
        },
        {
            "Sid": "Stmt1448539724000",
            "Effect": "Allow",
            "Action": [
                "lambda:GetFunction",
                "lambda:UpdateFunctionCode",
                "lambda:UpdateFunctionConfiguration"
            ],
            "Resource": [
                "arn:aws:lambda:*"
            ]
        },
        {
            "Sid": "Stmt1442787265773",
            "Action": [
                "iam:PassRole"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:iam::<aws account id>:role/<role name>"
        }
    ]
}
```

**Comment by taromero** [comment]
Thanks for the hints! I didn't have time yet to try this out but I'll let you know how it went later today.

**Comment by taromero** [comment]
Sorry for the late reply. I've tried this, creating a new user with only this policy attached (replacing the variables), and using those user's credentials on the Gruntfile to run the deploy, but I'm getting the exact same problem. I've checked which credentials are used using the --verbose options, and the new ones are being used.

Just to be sure, you can't reproduce the issue with your current policy right?

Thanks!

**Comment by taromero** [comment]
Could you share the policy you have attached to your Lambda exec role?

Mine is:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "logs:*"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Action": [
                "s3:*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

**Comment by taromero** [comment]
After further debugging, this seems unrelated to either grunt-aws-apigateway or the permissions on the policy attached to the IAM user.

This problem seems related to some restriction on the number of endpoints that can be attached to a Lambda function.

I'm closing this ticket, thanks for the support.

**Comment by pracucci** [comment]
Thanks for the update. Good to know, I was totally unaware of that.
