### ISSUE TITLE
Add option to set "API Key Required" to true

### ISSUE THREAD

**Issue by taromero** [spreaker/grunt-aws-apigateway#4]
Right now we have to manually set it to true (if that's what we want) for each endpoint, each time after rebuilding the API.

It would be cool to specify this option on the Grunt script.

**Comment by taromero** [comment]
Looking at the source I realized this option can be set, along with the method definition. For example:

```
...
GET: {
  integration: {...},
  apiKeyRequired: true,
  responses: {}
}
...
```

**Comment by pracucci** [comment]
I'm going to improve the documentation. I'm currently doing some experiments to figure out what's the easiest way to document it.
